language: node_js

matrix:
  fast_finish: true
  
node_js:
  - '5'
  - '4'

cache:
  directories:
    - src

before_install:
  - npm prune
  
deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: sprint1
